clc; clear; close all;
filename = 'noisysignal.wav';
[y, Fs] = audioread(filename); 
N = length(y);
t = (0:N-1) / Fs;
figure(1);
plot(t, y);
title('Raw Noisy Voltage Signal');
xlabel('Time (seconds)');
ylabel('Amplitude');
grid on;
Y = fft(y);
P2 = abs(Y / N);
P1 = P2(1:floor(N/2)+1);
P1(2:end-1) = 2 * P1(2:end-1);
f = Fs * (0:floor(N/2)) / N;
figure(2);
plot(f, P1);
title('Single-Sided Amplitude Spectrum');
xlabel('Frequency (Hz)');
ylabel('Magnitude');
xlim([0 200]);
grid on;
figure(3);
window = rectwin(1024);
noverlap = 512;
nfft = 1024;
spectrogram(y, window, noverlap, nfft, Fs, 'yaxis');
title('Spectrogram to Locate Glitch Time');
glitch_freq = 150;
glitch_time = 1720;
hrs = floor(glitch_time / 3600);
mins = floor(mod(glitch_time, 3600) / 60);
secs = mod(glitch_time, 60);
fprintf('The precise time instant of the glitch is: %02d hrs, %02d mins, %05.2f secs\n', hrs, mins, secs);
wo = glitch_freq / (Fs/2);     
bw = wo / 35;
[b_notch, a_notch] = iirnotch(wo, bw);
y_no_glitch = filtfilt(b_notch, a_notch, y);
f_low = 45;
f_high = 55;
Wn = [f_low f_high] / (Fs/2);  
order = 4;
[b_bp, a_bp] = butter(order, Wn, 'bandpass');
y_clean = filtfilt(b_bp, a_bp, y_no_glitch);
figure(4);
plot(t, y_clean);
title('Cleaned 50Hz Voltage Signal');
xlabel('Time (seconds)');
ylabel('Amplitude');
grid on;
V_rms_digital = rms(y_clean);
Grid_RMS_Actual = 230;
Scaling_Factor = Grid_RMS_Actual / V_rms_digital;
y_physical_volts = y_clean * Scaling_Factor;
fprintf('Signal successfully scaled to %f V RMS.\n', rms(y_physical_volts));
